version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d mydatabase" ]
      interval: 20s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    expose:
      - 80
    depends_on:
      - app
    volumes:
      - ./nginx:/etc/nginx/conf.d

  app:
    build:
      context: ../app
    restart: always
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000"]

  tests:
    environment:
      - TEST_ENVIRONMENT=1
    build:
      context: ../app
    depends_on:
      db:
        condition: service_healthy
    command: [ "pytest", "tests" ]
