version: '3'

services:
  app:
    build:
      context: ../app
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db
    command: ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8000"]

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
